# charts/prepare/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: zitadel
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
