apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-prometheus-scrape
rules:
  - apiGroups: [ "" ]
    resources: [ "pods","services","endpoints","namespaces","nodes","nodes/proxy" ]
    verbs: [ "get","list","watch" ]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "get","list","watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get","list","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-prometheus-scrape
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otelcol-prometheus-scrape
subjects:
  - kind: ServiceAccount
    name: otelcol-opentelemetry-collector
    namespace: monitoring
